# Generated by Django 4.1.7 on 2023-04-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='상품명')),
                ('code', models.CharField(max_length=16, verbose_name='상품코드')),
                ('description', models.CharField(max_length=16, verbose_name='상품설명')),
                ('price', models.CharField(max_length=16, verbose_name='상품가격')),
                ('stock', models.CharField(max_length=16, verbose_name='재고')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
            ],
        ),
    ]
